"""Post-process nanobot config for portable setup.

Usage:
    python post_config.py <config_path> <root_dir>

Reads the config generated by `nanobot onboard` and adds:
- Custom provider with env-var API key
- CLI channel
- Portable-friendly exec pathAppend
- Workspace path adjustment
"""

import json
import os
import sys


def main():
    if len(sys.argv) < 3:
        print("Usage: post_config.py <config_path> <root_dir>")
        sys.exit(1)

    config_path = sys.argv[1]
    root_dir = sys.argv[2]

    if not os.path.isfile(config_path):
        print(f"[ERROR] Config not found: {config_path}")
        sys.exit(1)

    # Backup before modification
    bak_path = config_path + '.bak'
    if not os.path.isfile(bak_path):
        import shutil
        shutil.copy2(config_path, bak_path)
        print(f"[BAK] Backup: {bak_path}")
    else:
        print(f"[BAK] Already available, skip: {bak_path}")

    with open(config_path, 'r', encoding='utf-8') as f:
        config = json.load(f)

    # === providers ===
    if 'providers' not in config:
        config['providers'] = {}
    config['providers']['custom'] = {
        "apiKey": "${NANOBOT_CUSTOM_API_KEY}",
        "apiBase": "${NANOBOT_CUSTOM_API_BASE}",
        "apiType": "auto"
    }

    # === agents.defaults ===
    defaults = config.get('agents', {}).get('defaults', {})
    defaults['model'] = 'sengkuni-1.0'
    defaults['provider'] = 'custom'
    # Don't override workspace if user already set it

    # === channels ===
    if 'channels' not in config:
        config['channels'] = {}
    config['channels']['cli'] = {"enabled": True}

    # === tools.exec ===
    tools = config.get('tools', {})
    exec_cfg = tools.get('exec', {})
    py_dir = os.path.join(root_dir, 'bin')
    scripts_dir = os.path.join(root_dir, 'scripts')
    git_cmd = os.path.join(root_dir, 'bin', 'git', 'cmd')
    nodejs_dir = os.path.join(root_dir, 'bin', 'nodejs')
    pwsh_dir = os.path.join(root_dir, 'bin', 'pwsh')
    path_parts = [p for p in [py_dir, scripts_dir, git_cmd, nodejs_dir, pwsh_dir] if os.path.isdir(p) or 'git' in p or 'nodejs' in p or 'pwsh' in p]
    exec_cfg['pathAppend'] = ';'.join(path_parts)
    exec_cfg['restrictToWorkspace'] = True
    tools['exec'] = exec_cfg

    # Also set top-level restrictToWorkspace
    tools['restrictToWorkspace'] = True

    # === write back ===
    with open(config_path, 'w', encoding='utf-8') as f:
        json.dump(config, f, indent=2, ensure_ascii=False)

    print(f"[OK] Config post-processed: {config_path}")


if __name__ == '__main__':
    main()
